// <auto-generated />
using System;
using AAI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AAI.Infrastructure.Migrations
{
    [DbContext(typeof(AAIDbContext))]
    partial class AAIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AAI.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssetClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("BRL");

                    b.Property<string>("Exchange")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsManualEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastPriceUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetClass");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("AAI.Domain.Entities.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("BRL");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Portfolios", (string)null);
                });

            modelBuilder.Entity("AAI.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AllocationPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("PortfolioId", "AssetId")
                        .IsUnique();

                    b.ToTable("Positions", (string)null);
                });

            modelBuilder.Entity("AAI.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Broker")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PositionId");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("TransactionType");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("AAI.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvestmentGoal")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RebalanceThresholdPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskProfile")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetAllocationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeHorizonMonths")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VolatilityTolerance")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("AAI.Domain.Entities.Asset", b =>
                {
                    b.OwnsOne("AAI.Domain.ValueObjects.Money", "CurrentPrice", b1 =>
                        {
                            b1.Property<Guid>("AssetId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 8)
                                .HasColumnType("TEXT")
                                .HasColumnName("CurrentPrice");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("BRL")
                                .HasColumnName("CurrentPriceCurrency");

                            b1.HasKey("AssetId");

                            b1.ToTable("Assets", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AssetId");
                        });

                    b.Navigation("CurrentPrice");
                });

            modelBuilder.Entity("AAI.Domain.Entities.Portfolio", b =>
                {
                    b.HasOne("AAI.Domain.Entities.UserProfile", "User")
                        .WithOne("Portfolio")
                        .HasForeignKey("AAI.Domain.Entities.Portfolio", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AAI.Domain.Entities.Position", b =>
                {
                    b.HasOne("AAI.Domain.Entities.Asset", "Asset")
                        .WithMany("Positions")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AAI.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("Positions")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AAI.Domain.ValueObjects.Money", "AverageCost", b1 =>
                        {
                            b1.Property<Guid>("PositionId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 8)
                                .HasColumnType("TEXT")
                                .HasColumnName("AverageCost");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("BRL")
                                .HasColumnName("AverageCostCurrency");

                            b1.HasKey("PositionId");

                            b1.ToTable("Positions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PositionId");
                        });

                    b.OwnsOne("AAI.Domain.ValueObjects.Money", "CurrentValue", b1 =>
                        {
                            b1.Property<Guid>("PositionId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 8)
                                .HasColumnType("TEXT")
                                .HasColumnName("CurrentValue");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("BRL")
                                .HasColumnName("CurrentValueCurrency");

                            b1.HasKey("PositionId");

                            b1.ToTable("Positions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PositionId");
                        });

                    b.OwnsOne("AAI.Domain.ValueObjects.Money", "TotalInvested", b1 =>
                        {
                            b1.Property<Guid>("PositionId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 8)
                                .HasColumnType("TEXT")
                                .HasColumnName("TotalInvested");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("BRL")
                                .HasColumnName("TotalInvestedCurrency");

                            b1.HasKey("PositionId");

                            b1.ToTable("Positions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PositionId");
                        });

                    b.OwnsOne("AAI.Domain.ValueObjects.Money", "UnrealizedGainLoss", b1 =>
                        {
                            b1.Property<Guid>("PositionId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 8)
                                .HasColumnType("TEXT")
                                .HasColumnName("UnrealizedGainLoss");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("BRL")
                                .HasColumnName("UnrealizedGainLossCurrency");

                            b1.HasKey("PositionId");

                            b1.ToTable("Positions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PositionId");
                        });

                    b.OwnsOne("AAI.Domain.ValueObjects.Percentage", "UnrealizedGainLossPercent", b1 =>
                        {
                            b1.Property<Guid>("PositionId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Value")
                                .HasPrecision(8, 4)
                                .HasColumnType("TEXT")
                                .HasColumnName("UnrealizedGainLossPercent");

                            b1.HasKey("PositionId");

                            b1.ToTable("Positions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PositionId");
                        });

                    b.Navigation("Asset");

                    b.Navigation("AverageCost")
                        .IsRequired();

                    b.Navigation("CurrentValue")
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("TotalInvested")
                        .IsRequired();

                    b.Navigation("UnrealizedGainLoss")
                        .IsRequired();

                    b.Navigation("UnrealizedGainLossPercent")
                        .IsRequired();
                });

            modelBuilder.Entity("AAI.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("AAI.Domain.Entities.Position", "Position")
                        .WithMany("Transactions")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AAI.Domain.ValueObjects.Money", "Fees", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 8)
                                .HasColumnType("TEXT")
                                .HasColumnName("Fees");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("BRL")
                                .HasColumnName("FeesCurrency");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.OwnsOne("AAI.Domain.ValueObjects.Money", "TotalValue", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 8)
                                .HasColumnType("TEXT")
                                .HasColumnName("TotalValue");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("BRL")
                                .HasColumnName("TotalValueCurrency");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.OwnsOne("AAI.Domain.ValueObjects.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<Guid>("TransactionId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 8)
                                .HasColumnType("TEXT")
                                .HasColumnName("UnitPrice");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("BRL")
                                .HasColumnName("UnitPriceCurrency");

                            b1.HasKey("TransactionId");

                            b1.ToTable("Transactions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TransactionId");
                        });

                    b.Navigation("Fees")
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("TotalValue")
                        .IsRequired();

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("AAI.Domain.Entities.Asset", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("AAI.Domain.Entities.Portfolio", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("AAI.Domain.Entities.Position", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("AAI.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("Portfolio");
                });
#pragma warning restore 612, 618
        }
    }
}
